#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HALF_SPEED 63;
#define FULL_SPEED 127;
#define STATIONARY 0;
#define BACK_HALF -63;
#define BACK_FULL -127;

/*
*runs a Motor at half backwards speed for .5 sec, stop for .5 sec,
*fullspeed for .5 sec, then stop
*/
void startTest(tMotor m)
{
	motor[m] = BACK_HALF;
	wait1Msec(500);
	motor[m] = STATIONARY;
	wait1Msec(500);
	motor[m] = FULL_SPEED;
	wait1Msec(500);
	motor[m] = STATIONARY;
}

/*
*turn left without moving forward, pivot turn
*/
void left(int time)
{
	motor[rightMotor] = HALF_SPEED;
	motor[leftMotor] = -HALF_SPEED;
	wait1Msec(time);
	motor[leftMotor] = STATIONARY;
	motor[rightMotor] = -STATIONARY;
}

void right(int time)
{
	motor[leftMotor] = HALF_SPEED;
	motor[rightMotor] = -HALF_SPEED;
	wait1Msec(time);
	motor[leftMotor] = STATIONARY;
	motor[rightMotor] = -STATIONARY;
}

task main()
{
	/*
	*Starts speed test, tests the turning mechanism
	*First turns left, then right
	*/
	startTest(rightMotor);
	wait1Msec (200);
	startTest(leftMotor);
	wait1Msec (200);
	left(1000);
	wait1Msec (200);
	right(1000);
}
