#pragma config(Sensor, in1,    temp,           sensorReflection)
#pragma config(Sensor, dgtl1,  wind,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ledBoop,        sensorDigitalOut)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           flag,          tmotorNone, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*everything on the left is negated because of mirrored motors
*/
#define HALF_SPEED 63;
#define FULL_SPEED 127;
#define STATIONARY 0;
#define BACK_HALF -63;
#define BACK_FULL -127;

/*
*turn left without moving forward, pivot turn
*/
void left()
{
	motor[rightMotor] = 63;
	motor[leftMotor] = 63;
	wait1Msec(500);
}

void right()
{
	motor[leftMotor] = -63;
	motor[rightMotor] = -63;
	wait1Msec(500);
}
void dropFlag()
{
	motor[flag] = 30;
	wait1Msec(500);
	motor[flag] = STATIONARY;
}
void testLightSense()
{
	writeDebugStreamLine("sensor value: %d", SensorValue[temp]);
}
/*
* meaure for ten seconds, every second
*/
void lightSense()
{
	int temps[10];
	for (int i = 0; i < 10; i++)
	{
		temps[i] = SensorValue[temp];
		wait1Msec(1000);
		writeDebugStreamLine("sensor value: %d", SensorValue[temp]);
	}
}

void move()
{
	while(true) {
		if(vexRT[Btn7u] == 1){
			motor[rightMotor] = HALF_SPEED;
			motor[leftMotor] = -HALF_SPEED;
		}
		else if(vexRT[Btn7d] == 1){
			motor[rightMotor] = -HALF_SPEED;
			motor[leftMotor] = HALF_SPEED;
		}
		else if(vexRT[Btn7r] == 1){
			motor[rightMotor] = -HALF_SPEED;
			motor[leftMotor] = -HALF_SPEED;
		}
		else if(vexRT[Btn7l] == 1){
			motor[rightMotor] = HALF_SPEED;
			motor[leftMotor] = HALF_SPEED;
		}
		else{
			motor[rightMotor] = STATIONARY;
			motor[leftMotor] = STATIONARY;
		}
		if(vexRT[Btn6D] == 1){
			dropFlag();
		}
		if(vexRT[Btn6U] == 1){
			lightSense();
		}
	}
}

task main()
{
	left();
	right();
	move();//sweet
}
