#pragma config(Motor,  port1,           backLeftMotor, tmotorNone, openLoop)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port4,           frontRightMotor, tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port10,          backRightMotor, tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HALF_SPEED 63;
#define FULL_SPEED 127;
#define STATIONARY 0;
#define BACK_HALF -63;
#define BACK_FULL -127;

/*
*runs a Motor at half speed for .5 sec, stop for .5 sec,
*fullspeed for .5 sec, then stop
*/
void startTest(tMotor m)
{
	motor[m] = 127;
	wait1Msec(500);
	motor[m] = STATIONARY;
	wait1Msec(500);
	motor[m] = FULL_SPEED;
	wait1Msec(500);
	motor[m] = STATIONARY;

}

task main()
{
	tMotor m = motor[frontRightMotor];
	m=127;
	motor[frontLeftMotor] = 127;
	startTest(motor[frontRightMotor]);
	startTest(motor[frontLeftMotor]);
	startTest(motor[backRightMotor]);
	startTest(motor[backLeftMotor]);
}
